# Generated by Django 4.1.3 on 2022-11-22 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('starts', models.DateTimeField()),
                ('match_status', models.CharField(choices=[('upcoming', 'Up Coming'), ('live', 'Live'), ('ended', 'ended'), ('cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('time', models.PositiveSmallIntegerField()),
                ('player', models.CharField(max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='match.match')),
                ('teams', models.ManyToManyField(related_name='scores', to='match.team')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='participated_matches', to='match.team'),
        ),
    ]
