# Generated by Django 4.1.3 on 2022-11-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamscore',
            name='teams',
        ),
        migrations.AddField(
            model_name='teamscore',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='match.team'),
            preserve_default=False,
        ),
    ]
