# Generated by Django 4.1.3 on 2022-11-25 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_remove_teamscore_teams_teamscore_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('time', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='match.match')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
